import numpy as np
x1=np.array([[4,2],[2,4],[2,3],[3,6],[4,4]])
x1size=x1.shape[0]
x2=np.array([[9,10],[6,8],[9,5],[8,7],[10,8]])
x2size=x2.shape[0]
mu1=np.mean(x1,axis=0)
print(mu1)
z1=(x1-mu1)
s1=np.dot(z1.T,z1)/(x1size-1)
print("Cov of first class")
print(s1)
mu2=np.mean(x2,axis=0)
print(mu2)
z2=(x2-mu2)
print(z2)
s2=np.dot(z2.T,z2)/(x2size-1)
print("Cov of second class")
print(s2)
print("within class scatter")
sw=s1+s2
print(sw)
mu=[]
mu.append(mu1)
mu.append(mu2)
mu=np.asarray(mu)
print(mu)
mudiff=(mu[0:1,:].T-mu[1:2,:].T)
print(mudiff)
sb=np.dot(mudiff,mudiff.T)
print("Between class scatter")
print(sb)
print("Sw inverse")
inv=np.linalg.inv(sw)
print(inv)
evalues,evecs=np.linalg.eig(np.dot(inv,sb))
print(evalues)
print(evecs)
print(np.dot(x1,evecs[:,0:1]))
print(np.dot(x2,evecs[:,0:1]))
